spring:
  application:
    name: react-blog-boot
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 200381
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    #    password: 200381
  elasticsearch:
    uris: 192.168.91.132:9200


server:
  servlet:
    context-path: /deslre
  port: 8080

custom:
  #  static-source-path: /opt/staticSource
  static-source-path: E:\\staticSource
